"""
export.py — read expenses.db + config.json and write data.js next to the
dashboard.

data.js defines two globals that dashboard.html loads via a plain
<script src="data.js"> tag (NOT fetch), so the dashboard works from
file:// with zero server:

    window.EXPENSE_DATA = [ {id, date, category, amount, note, type, ...}, ... ];
    window.EXPENSE_CONFIG = { currency, monthlyBudget, budgets };

The bot token is read from config.json here on the Python side only —
it is never written into data.js / never reaches the browser.

Run directly to regenerate data.js once:
    python export.py
The bot calls run_export() after every logged message.
"""

import json
import os
from pathlib import Path

import db

HERE = Path(__file__).parent
CONFIG_PATH = HERE / "config.json"
if not CONFIG_PATH.exists():
    CONFIG_PATH = HERE / "config.example.json"
DASHBOARD_DIR = HERE  # data.js is written next to dashboard.html
DATA_JS_PATH = DASHBOARD_DIR / "data.js"


def load_config():
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        config = json.load(f)
    config["telegram_token"] = os.environ.get("TELEGRAM_TOKEN", config.get("telegram_token"))
    config["supabase_url"] = os.environ.get("SUPABASE_URL", config.get("supabase_url"))
    config["supabase_key"] = os.environ.get("SUPABASE_KEY", config.get("supabase_key"))
    return config


def run_export(db_path=None, out_path=None):
    """Regenerate data.js from the current DB + config. Returns the path written."""
    config = load_config()
    rows = db.all_rows(db_path=db_path)

    # Strip chat_id before it reaches the browser file — it's not needed
    # for the dashboard and there's no reason to expose it.
    safe_rows = [
        {
            "id": r["id"],
            "date": r["date"],
            "category": r["category"],
            "amount": r["amount"],
            "note": r["note"],
            "type": r["type"],
            "created_at": r["created_at"],
        }
        for r in rows
    ]

    public_config = {
        "currency": config.get("currency", "₹"),
        "monthlyBudget": config.get("monthlyBudget", 0),
        "budgets": config.get("budgets", {}),
    }

    js = (
        "// Auto-generated by export.py — do not edit by hand.\n"
        "// Regenerated after every transaction logged via the Telegram bot.\n"
        f"window.EXPENSE_DATA = {json.dumps(safe_rows, ensure_ascii=False, indent=2)};\n"
        f"window.EXPENSE_CONFIG = {json.dumps(public_config, ensure_ascii=False, indent=2)};\n"
    )

    target = out_path or DATA_JS_PATH
    with open(target, "w", encoding="utf-8") as f:
        f.write(js)

    return target


if __name__ == "__main__":
    path = run_export()
    print(f"Wrote {path}")
